language: r

branches:
  only:
    - source

cache: packages
r_github_packages:
    - rstudio/blogdown
before_script:
  - Rscript -e 'blogdown::install_hugo()'
script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  local_dir: public
  target_branch: master
